# Auto-captured real grids from the Bunnings PDF. Do not hand-edit.

WAGE_TABLES = [[['',
   '',
   '',
   '',
   'Bunnings Warehouse',
   '',
   '',
   'Bunnings Trade',
   '',
   '',
   'Hourly Wage Rates September 2023',
   None,
   None,
   None,
   ''],
  ['Grade',
   'Grade',
   None,
   'Role',
   'Role',
   None,
   'Role',
   'Role',
   None,
   'Base Rate',
   'Base Rate',
   None,
   '',
   'Casual Hourly',
   ''],
  [None, None, None, None, None, None, None, None, None, None, None, None, None, 'Rate', None],
  ['Team Member',
   None,
   None,
   'Store Team Member',
   None,
   None,
   '',
   'Trade Team Member',
   '',
   '$27.00',
   None,
   None,
   '$33.08',
   None,
   None],
  [None, None, None, None, None, None, '', 'Customer Service Operator', '', None, None, None, None, None, None],
  ['Team Member\n(Expert)',
   None,
   None,
   '',
   'Expert Team Member',
   '',
   'N/A',
   None,
   None,
   '$27.43',
   None,
   None,
   '$33.60',
   None,
   None],
  [None, None, None, '', 'Special Orders, Service', '', None, None, None, None, None, None, None, None, None],
  [None, None, None, None, '& Trade Desk Team', None, None, None, None, None, None, None, None, None, None],
  [None, None, None, None, 'Member', None, None, None, None, None, None, None, None, None, None],
  ['Specialists',
   None,
   None,
   'Forklift Operator',
   'Forklift Operator',
   None,
   'Forklift Operator',
   None,
   None,
   '$28.15',
   None,
   None,
   '$34.49',
   None,
   None],
  [None, None, None, '', 'Kitchen Specialist', '', '', 'Trade Administrator', '', None, None, None, None, None, None],
  [None, None, None, '', 'Activities Organiser', '', 'N/A', 'N/A', None, None, None, None, None, None, None],
  [None, None, None, '', 'Store Administrator', '', None, None, None, None, None, None, None, None, None],
  [None, None, None, '', 'Inventory Specialist', '', None, None, None, None, None, None, None, None, None],
  [None, None, None, '', 'Forklift Coach', '', '', 'Forklift Coach', '', '$28.42', None, None, '$34.82', None, None],
  [None,
   None,
   None,
   'Trade Qualified TM',
   'Trade Qualified TM',
   None,
   '',
   'Trade Qualified Customer',
   '',
   None,
   None,
   None,
   None,
   None,
   None],
  [None, None, None, None, None, None, None, 'Service Operator', None, None, None, None, None, None, None],
  [None, None, None, '', 'Trade Specialist', '', '', 'N/A', '', None, None, None, None, None, None],
  ['', 'Supervisor', '', '', 'Supervisor', '', '', 'Supervisor', '', '', '$29.01', '', '', '$35.54', '']],
 [['Team Member'], ['(Expert)']]]

REDUNDANCY_TABLES = [[['Period of Continuous\nService', '', 'Weeks’ redundancy pay (calculated at', None, None, ''],
  [None, None, 'the Team Member’s Contract Rate)', None, None, None],
  [None, '', 'Team Members', '', 'Team Members\naged 45 and over', None],
  [None, None, 'under 45 years', None, None, None],
  [None, None, 'of age', None, None, None],
  ['less than 1 year', 'Nil', None, None, 'Nil', None],
  ['1 year but less than 2 years', '4', None, None, '5', None],
  ['2 years but less than 3 years', '7', None, None, '9', None],
  ['3 years but less than 4 years', '10', None, None, '13', None],
  ['4 years but less than 5 years', '12', None, None, '15', None],
  ['5 years but less than 6 years', '14', None, None, '18', None],
  ['6 years and more', '16', None, None, '20', None]],
 [['Period of Continuous'], ['Service']],
 [['Team Members'], ['aged 45 and over']]]
